# Generated by Skyramp v1.3.11 on 2026-03-11 13:25:31.439971679 +0000 UTC m=+101.461898059
# Command: skyramp generate contract rest http://localhost:8000/items/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_items_post_category_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--request-data {"name":"Laptop Pro","description":"High-performance laptop","price":999.99,"tax":89.99,"category":"electronics"} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /items/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
        "category": "electronics",
        "description": "High-performance laptop",
        "name": "Laptop Pro",
        "price": 999.99,
        "tax": 89.99
    }'''

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/items/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_POST_response.status_code == 201

if __name__ == "__main__":
    test_endpoint_post()
