# Generated by Skyramp v1.3.11 on 2026-03-11 13:55:42.242583526 +0000 UTC m=+230.785624287
# Command: skyramp generate integration rest \
# 		--auth-header X-API-Key \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_category_crud.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/fastapi-testb/fastapi-testb/tests/scenario_items-category-crud.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "category": "electronics",
        "description": "High performance laptop",
        "name": "Laptop Pro",
        "price": 999.99,
        "tax": 89.99
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    items_GET_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="GET",
        headers={"X-API-Key": ""},
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_GET_response.status_code == 200

    # Request Body
    items_PUT_request_body = r'''{
        "category": "electronics",
        "description": "Updated high performance laptop",
        "name": "Laptop Pro Max",
        "price": 1199.99,
        "tax": 107.99
    }'''
    
    # Execute Request
    items_PUT_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="PUT",
        body=items_PUT_request_body,
        headers={"X-API-Key": ""},
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")},
        data_override={"category": skyramp.get_response_value(items_GET_response, "category")}
    )
    # Generated Assertions
    assert items_PUT_response.status_code == 200

    # Execute Request
    items_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="DELETE",
        headers={"X-API-Key": ""},
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_DELETE_response.status_code == 204

if __name__ == "__main__":
    test_integration()
