# Generated by Skyramp v1.3.11 on 2026-03-09 20:44:05.355132558 +0000 UTC m=+141.151524928
# Command: skyramp generate integration rest \
# 		--auth-header X-API-Key \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_create_and_list.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/fastapi-testb/fastapi-testb/tests/scenario_items-create-and-list.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "category": "electronics",
        "description": "A test electronics item",
        "name": "Electronics Widget",
        "price": 29.99,
        "tax": 2.5
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="GET",
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
