# Generated by Skyramp v1.3.11 on 2026-03-11 13:56:00.041152516 +0000 UTC m=+248.584193277
# Command: skyramp generate integration rest \
# 		--auth-header X-API-Key \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_category_validation.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/fastapi-testb/fastapi-testb/tests/scenario_items-category-validation.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "description": "A test book",
        "name": "Test Book",
        "price": 19.99
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 422

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "category": "invalid_category",
        "description": "A test book",
        "name": "Test Book",
        "price": 19.99
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 422

    # Request Body
    endpoint_1_POST_2_request_body = r'''{
        "category": "books",
        "description": "A comprehensive Python programming book",
        "name": "Python Cookbook",
        "price": 49.99,
        "tax": 4.5
    }'''
    
    # Execute Request
    endpoint_1_POST_2_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_2_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_2_response.status_code == 201

if __name__ == "__main__":
    test_integration()
