# Generated by Skyramp v1.3.11 on 2026-03-09 19:30:28.064285944 +0000 UTC m=+110.649356625
# Command: skyramp generate contract rest http://localhost:8000/items/ \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# Definition of authentication header
def get_header():
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")
    return headers


# contract test for /items/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Expected Response Body
    expected_endpoint_GET_response_body = r'''[
        {}
    ]'''

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/items/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert endpoint_GET_response.status_code == 200
    assert skyramp.check_schema(endpoint_GET_response, expected_endpoint_GET_response_body)
    assert skyramp.get_response_value(endpoint_GET_response, "0") is not None



# contract test for /items/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Request Body — price must be > 0, tax must be a valid number (Pydantic validation)
    endpoint_POST_request_body = r'''{
        "description": "contract test item",
        "name": "Contract Item",
        "price": 9.99,
        "tax": 0.5
    }'''

    # Expected Response Body
    expected_endpoint_POST_response_body = r'''{}'''

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/items/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_POST_response.status_code == 201
    assert skyramp.check_schema(endpoint_POST_response, expected_endpoint_POST_response_body)



# contract test for /items/{item_id} GET
def test_items_item_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Create an item first so we have a valid item_id
    create_body = r'''{"name": "Contract Get Item", "price": 5.00, "tax": 0.0}'''
    create_response = client.send_request(url=URL, path="/items/", method="POST", body=create_body, headers=headers)
    item_id = skyramp.get_response_value(create_response, "id")

    # Expected Response Body
    expected_items_item_id_GET_response_body = r'''{}'''

    # Execute Request
    items_item_id_GET_response = client.send_request(
        url=URL,
        path="/items/{item_id}",
        method="GET",
        headers=headers,
        path_params={"item_id": item_id}
    )

    # Generated Assertions
    assert items_item_id_GET_response.status_code == 200
    assert skyramp.check_schema(items_item_id_GET_response, expected_items_item_id_GET_response_body)



# contract test for /items/{item_id} PUT
def test_items_item_id_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Create an item first so we have a valid item_id
    create_body = r'''{"name": "Contract Put Item", "price": 5.00, "tax": 0.0}'''
    create_response = client.send_request(url=URL, path="/items/", method="POST", body=create_body, headers=headers)
    item_id = skyramp.get_response_value(create_response, "id")

    # Request Body — price must be > 0, tax must be a valid number (Pydantic validation)
    items_item_id_PUT_request_body = r'''{
        "description": "updated contract item",
        "name": "Updated Contract Item",
        "price": 19.99,
        "tax": 1.5
    }'''

    # Expected Response Body
    expected_items_item_id_PUT_response_body = r'''{}'''

    # Execute Request
    items_item_id_PUT_response = client.send_request(
        url=URL,
        path="/items/{item_id}",
        method="PUT",
        body=items_item_id_PUT_request_body,
        headers=headers,
        path_params={"item_id": item_id}
    )

    # Generated Assertions
    assert items_item_id_PUT_response.status_code == 200
    assert skyramp.check_schema(items_item_id_PUT_response, expected_items_item_id_PUT_response_body)



# contract test for /items/{item_id} DELETE
def test_items_item_id_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Create an item first so we have a valid item_id
    create_body = r'''{"name": "Contract Delete Item", "price": 5.00, "tax": 0.0}'''
    create_response = client.send_request(url=URL, path="/items/", method="POST", body=create_body, headers=headers)
    item_id = skyramp.get_response_value(create_response, "id")

    # Execute Request
    items_item_id_DELETE_response = client.send_request(
        url=URL,
        path="/items/{item_id}",
        method="DELETE",
        headers=headers,
        path_params={"item_id": item_id}
    )

    # Generated Assertions
    assert items_item_id_DELETE_response.status_code == 204

if __name__ == "__main__":
    test_endpoint_get()
    test_endpoint_post()
    test_items_item_id_get()
    test_items_item_id_put()
    test_items_item_id_delete()
