# Generated by Skyramp v1.3.11 on 2026-03-11 11:18:41.78004745 +0000 UTC m=+147.461925013
# Command: skyramp generate fuzz rest http://localhost:8000/items/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_items_post_fuzz.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--request-data {"name":"Widget Pro","description":"A professional-grade widget","price":29.99,"tax":2.50} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# fuzz test for /items/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
      "category": "electronics",
      "name": "Widget Pro",
      "description": "A professional-grade widget",
      "price": 29.99,
      "tax": 2.50
    }'''
    
    # Fuzz strategies
    endpoint_post_fuzzed_body = {
        "description": "0123456789",
        "name": "0123456789",
        "price": -10,
        "tax": -10
    }
    # Fuzz status codes
    expected_endpoint_post_status_code = {
        "description": "40x",
        "name": "40x",
        "price": "40x",
        "tax": "40x"
    }
    # Fuzz status codes for Null values
    expected_endpoint_post_null_status_code = {
        "description": "40x",
        "name": "40x",
        "price": "40x",
        "tax": "40x"
    }

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/items/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(endpoint_post_fuzzed_body):
        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/items/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(endpoint_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_endpoint_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(endpoint_post_fuzzed_body, key) }'
        )

        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/items/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_endpoint_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_post()
