# Generated by Skyramp v1.3.11 on 2026-03-09 20:43:58.423490042 +0000 UTC m=+134.219882422
# Command: skyramp generate contract rest http://localhost:8000/items/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_items_list_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /items/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/items/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(endpoint_GET_response, "20x")

if __name__ == "__main__":
    test_endpoint_get()
