# Generated by Skyramp v1.3.11 on 2026-03-09 19:30:31.593595277 +0000 UTC m=+114.178665970
# Command: skyramp generate integration rest \
# 		--auth-header X-API-Key \
# 		--chaining-key id \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_integration.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/fastapi-testb/fastapi-testb/tests/scenario_items-crud-lifecycle.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "description": "A test item",
        "name": "Test Item",
        "price": 9.99,
        "tax": 0.5
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    items_GET_response = client.send_request(
        url=URL_localhost,
        path="/items/{item_id}",
        method="GET",
        headers=headers,
        path_params={"item_id": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_GET_response.status_code == 200

    # Request Body
    items_PUT_request_body = r'''{
        "description": "An updated item",
        "name": "Updated Item",
        "price": 19.99,
        "tax": 1.5
    }'''
    
    # Execute Request
    items_PUT_response = client.send_request(
        url=URL_localhost,
        path="/items/{item_id}",
        method="PUT",
        body=items_PUT_request_body,
        headers=headers,
        path_params={"item_id": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_PUT_response.status_code == 200

    # Execute Request
    items_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/items/{item_id}",
        method="DELETE",
        headers=headers,
        path_params={"item_id": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_DELETE_response.status_code == 204

if __name__ == "__main__":
    test_integration()
