# Generated by Skyramp v1.3.11 on 2026-03-11 11:34:57.008789497 +0000 UTC m=+217.097270898
# Command: skyramp generate contract rest http://localhost:8000/items/ \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_items_list_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /items/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_endpoint_GET_response_body = r'''"string"'''

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/items/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert endpoint_GET_response.status_code == 200
    assert skyramp.check_schema(endpoint_GET_response, expected_endpoint_GET_response_body)

if __name__ == "__main__":
    test_endpoint_get()
