# Generated by Skyramp v1.3.11 on 2026-03-11 11:35:21.532044045 +0000 UTC m=+241.620525447
# Command: skyramp generate integration rest \
# 		--auth-header X-API-Key \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_pydantic_validation.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/fastapi-testb/fastapi-testb/tests/scenario_items-pydantic-validation.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "category": "electronics",
        "description": "A test widget for validation",
        "name": "Test Widget",
        "price": 19.99,
        "tax": 1.5
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    items_PUT_request_body = r'''{
        "category": "electronics",
        "description": "Update with negative price",
        "name": "Invalid Widget",
        "price": -5,
        "tax": 0
    }'''
    
    # Execute Request
    items_PUT_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="PUT",
        body=items_PUT_request_body,
        headers={"X-API-Key": ""},
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_PUT_response.status_code == 422

if __name__ == "__main__":
    test_integration()
