# Generated by Skyramp v1.3.11 on 2026-03-11 13:00:37.096228825 +0000 UTC m=+181.498836291
# Command: skyramp generate contract rest http://localhost:8000/items/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_items_post_with_category_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--request-data {"name":"Python Book","description":"Advanced Python programming guide","price":49.99,"tax":4.99,"category":"books"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /items/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
        "category": "books",
        "description": "Advanced Python programming guide",
        "name": "Python Book",
        "price": 49.99,
        "tax": 4.99
    }'''

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/items/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(endpoint_POST_response, "20x")

if __name__ == "__main__":
    test_endpoint_post()
