# Generated by Skyramp v1.3.11 on 2026-03-09 18:58:30.037238538 +0000 UTC m=+102.808759273
# Command: skyramp generate contract rest http://localhost:8000/items/ \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_items_post_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--request-data {"name":"Widget Pro","description":"A premium widget","price":29.99,"tax":2.5} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /items/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
        "description": "A premium widget",
        "name": "Widget Pro",
        "price": 29.99,
        "tax": 2.5
    }'''

    # Expected Response Body
    expected_endpoint_POST_response_body = r'''{}'''

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/items/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_POST_response.status_code == 201
    assert skyramp.check_schema(endpoint_POST_response, expected_endpoint_POST_response_body)

if __name__ == "__main__":
    test_endpoint_post()
