# Generated by Skyramp v1.3.11 on 2026-03-09 19:30:52.120395643 +0000 UTC m=+134.705466337
# Command: skyramp generate fuzz rest http://localhost:8000/items/ \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_fuzz.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# Definition of authentication header
def get_header():
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")
    return headers


# fuzz test for /items/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/items/",
        method="GET",
        headers=headers,
        expected_code="20x"
    )

    assert client.is_success()




# fuzz test for /items/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()

    # Request Body
    endpoint_POST_request_body = r'''{
            "description": "string",
            "name": "string",
            "price": 0,
            "tax": "string"
        }'''
    
    # Fuzz strategies
    endpoint_post_fuzzed_body = {
        "description": "0123456789",
        "name": "0123456789",
        "price": -10,
        "tax": "0123456789"
    }
    # Fuzz status codes
    expected_endpoint_post_status_code = {
        "description": "40x",
        "name": "40x",
        "price": "40x",
        "tax": "40x"
    }
    # Fuzz status codes for Null values
    expected_endpoint_post_null_status_code = {
        "description": "40x",
        "name": "40x",
        "price": "40x",
        "tax": "40x"
    }

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/items/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(endpoint_post_fuzzed_body):
        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/items/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(endpoint_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_endpoint_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(endpoint_post_fuzzed_body, key) }'
        )

        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/items/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_endpoint_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()




# fuzz test for /items/{item_id} GET
def test_items_item_id_get():
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()

    # Declaration of variables
    item_id = 0

    # Execute Request
    items_item_id_GET_response = client.send_request(
        url=URL,
        path="/items/{item_id}",
        method="GET",
        headers=headers,
        path_params={"item_id": item_id},
        expected_code="20x"
    )

    assert client.is_success()




# fuzz test for /items/{item_id} PUT
def test_items_item_id_put():
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()

    # Declaration of variables
    item_id = 0

    # Request Body
    items_item_id_PUT_request_body = r'''{
            "description": "string",
            "name": "string",
            "price": 0,
            "tax": "string"
        }'''
    
    # Fuzz strategies
    items_item_id_put_fuzzed_body = {
        "description": "0123456789",
        "name": "0123456789",
        "price": -10,
        "tax": "0123456789"
    }
    # Fuzz status codes
    expected_items_item_id_put_status_code = {
        "description": "40x",
        "name": "40x",
        "price": "40x",
        "tax": "40x"
    }
    # Fuzz status codes for Null values
    expected_items_item_id_put_null_status_code = {
        "description": "40x",
        "name": "40x",
        "price": "40x",
        "tax": "40x"
    }

    # Execute Request
    items_item_id_PUT_response = client.send_request(
        url=URL,
        path="/items/{item_id}",
        method="PUT",
        body=items_item_id_PUT_request_body,
        headers=headers,
        path_params={"item_id": item_id},
        expected_code="20x"
    )

    for key in skyramp.iterate(items_item_id_put_fuzzed_body):
        # Execute Request
        items_item_id_PUT_response = client.send_request(
            url=URL,
            path="/items/{item_id}",
            method="PUT",
            body=items_item_id_PUT_request_body,
            headers=headers,
            path_params={"item_id": item_id},
            data_override={key: skyramp.get_value(items_item_id_put_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_items_item_id_put_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(items_item_id_put_fuzzed_body, key) }'
        )

        # Execute Request
        items_item_id_PUT_response = client.send_request(
            url=URL,
            path="/items/{item_id}",
            method="PUT",
            body=items_item_id_PUT_request_body,
            headers=headers,
            path_params={"item_id": item_id},
            data_override={key: None},
            expected_code=skyramp.get_value(expected_items_item_id_put_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()




# fuzz test for /items/{item_id} DELETE
def test_items_item_id_delete():
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()

    # Declaration of variables
    item_id = 0

    # Execute Request
    items_item_id_DELETE_response = client.send_request(
        url=URL,
        path="/items/{item_id}",
        method="DELETE",
        headers=headers,
        path_params={"item_id": item_id},
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_get()
    test_endpoint_post()
    test_items_item_id_get()
    test_items_item_id_put()
    test_items_item_id_delete()
