# Generated by Skyramp v1.3.11 on 2026-03-11 11:34:56.821323089 +0000 UTC m=+216.909804491
# Command: skyramp generate contract rest http://localhost:8000/items/1 \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_items_get_by_id_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--path-params item_id=1 \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /items/{item_id} GET
def test_endpoint_1_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Create item first to get a valid ID (required by new category field)
    setup_request_body = r'''{
        "category": "books",
        "description": "Contract test item",
        "name": "Contract Widget",
        "price": 15.99,
        "tax": 1.5
    }'''
    setup_response = client.send_request(
        url=URL,
        path="/items/",
        method="POST",
        body=setup_request_body,
        headers=headers
    )
    assert setup_response.status_code == 201
    item_id = skyramp.get_response_value(setup_response, "id")

    # Expected Response Body (item object with required category field)
    expected_endpoint_1_GET_response_body = r'''{"id": 1, "name": "string", "description": "string", "price": 1.0, "tax": 1.0, "category": "books"}'''

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL,
        path="/items/{item_id}",
        method="GET",
        headers=headers,
        path_params={"item_id": item_id}
    )

    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200
    assert skyramp.check_schema(endpoint_1_GET_response, expected_endpoint_1_GET_response_body)

if __name__ == "__main__":
    test_endpoint_1_get()
