# Generated by Skyramp v1.3.11 on 2026-03-11 11:18:06.460204305 +0000 UTC m=+112.142081868
# Command: skyramp generate integration rest \
# 		--auth-header X-API-Key \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_crud_lifecycle.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/fastapi-testb/fastapi-testb/tests/scenario_items-crud-lifecycle.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "description": "A professional-grade widget",
        "name": "Widget Pro",
        "price": 29.99,
        "tax": 2.5
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    items_GET_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="GET",
        headers={"X-API-Key": ""},
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_GET_response.status_code == 200

    # Request Body
    items_PUT_request_body = r'''{
        "description": "An updated professional-grade widget",
        "name": "Widget Pro Updated",
        "price": 39.99,
        "tax": 3.5
    }'''
    
    # Execute Request
    items_PUT_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="PUT",
        body=items_PUT_request_body,
        headers={"X-API-Key": ""},
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_PUT_response.status_code == 200

    # Execute Request
    items_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="DELETE",
        headers={"X-API-Key": ""},
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_DELETE_response.status_code == 204

if __name__ == "__main__":
    test_integration()
