# Generated by Skyramp v1.3.11 on 2026-03-09 20:44:17.02344016 +0000 UTC m=+152.819832540
# Command: skyramp generate contract rest http://localhost:8000/items/1 \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output test_items_put_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--request-data {"name":"Updated Widget","description":"An updated widget","price":39.99,"tax":3.00,"category":"electronics"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /items/1 PUT
def test_endpoint_1_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_PUT_request_body = r'''{
        "category": "electronics",
        "description": "An updated widget",
        "name": "Updated Widget",
        "price": 39.99,
        "tax": 3
    }'''

    # Execute Request
    endpoint_1_PUT_response = client.send_request(
        url=URL,
        path="/items/1",
        method="PUT",
        body=endpoint_1_PUT_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(endpoint_1_PUT_response, "20x")

if __name__ == "__main__":
    test_endpoint_1_put()
