# Generated by Skyramp v1.3.11 on 2026-03-11 13:55:06.896091567 +0000 UTC m=+195.439132328
# Command: skyramp generate contract rest http://localhost:8000/items/1 \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output test_items_delete_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--path-params item_id=1 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /items/1 DELETE
def test_endpoint_1_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_1_DELETE_response = client.send_request(
        url=URL,
        path="/items/1",
        method="DELETE",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(endpoint_1_DELETE_response, "20x")

if __name__ == "__main__":
    test_endpoint_1_delete()
