# Generated by Skyramp v1.3.11 on 2026-03-11 12:21:22.992398881 +0000 UTC m=+247.802084167
# Command: skyramp generate contract rest http://localhost:8000/items/1 \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output test_items_put_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--path-params item_id=1 \
# 		--request-data {"name":"Updated Item","description":"Updated description","price":29.99,"tax":2.99,"category":"clothing"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /items/1 PUT
def test_endpoint_1_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_PUT_request_body = r'''{
        "category": "clothing",
        "description": "Updated description",
        "name": "Updated Item",
        "price": 29.99,
        "tax": 2.99
    }'''

    # Expected Response Body
    expected_endpoint_1_PUT_response_body = r'''"string"'''

    # Execute Request
    endpoint_1_PUT_response = client.send_request(
        url=URL,
        path="/items/1",
        method="PUT",
        body=endpoint_1_PUT_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_PUT_response.status_code == 200
    assert skyramp.check_schema(endpoint_1_PUT_response, expected_endpoint_1_PUT_response_body)

if __name__ == "__main__":
    test_endpoint_1_put()
