# Generated by Skyramp v1.3.11 on 2026-03-11 12:22:02.557668063 +0000 UTC m=+287.367353339
# Command: skyramp generate integration rest \
# 		--auth-header X-API-Key \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_category_validation.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/fastapi-testb/fastapi-testb/tests/scenario_items-category-validation-errors.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "description": "Missing category field",
        "name": "Test Item",
        "price": 19.99,
        "tax": 2
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 422

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "category": "gadgets",
        "description": "Invalid category value",
        "name": "Test Item",
        "price": 19.99,
        "tax": 2
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 422

    # Request Body
    endpoint_1_POST_2_request_body = r'''{
        "category": "food",
        "description": "Freshly baked sourdough",
        "name": "Organic Bread",
        "price": 6.99,
        "tax": 0.5
    }'''
    
    # Execute Request
    endpoint_1_POST_2_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_2_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_2_response.status_code == 201

    # Execute Request
    items_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/items/{items}",
        method="DELETE",
        headers={"X-API-Key": ""},
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_2_response, "id")}
    )
    # Generated Assertions
    assert items_DELETE_response.status_code == 204

if __name__ == "__main__":
    test_integration()
