# Generated by Skyramp v1.3.11 on 2026-03-09 19:57:03.438447106 +0000 UTC m=+126.331234922
# Command: skyramp generate contract rest http://localhost:8000/items/99999 \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_items_get_404_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--response-status-code 404 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /items/99999 GET
def test_endpoint_99999_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    endpoint_99999_GET_response = client.send_request(
        url=URL,
        path="/items/99999",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert endpoint_99999_GET_response.status_code == 404

if __name__ == "__main__":
    test_endpoint_99999_get()
