# Generated by Skyramp v1.3.11 on 2026-03-11 12:30:39.981238602 +0000 UTC m=+194.503743082
# Command: skyramp generate fuzz rest http://localhost:8000/items/1 \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output test_items_put_category_fuzz.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--path-params item_id=1 \
# 		--request-data {"name":"Updated Item","description":"Updated widget description","price":39.99,"tax":3.50,"category":"electronics"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# fuzz test for /items/1 PUT
def test_endpoint_1_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_PUT_request_body = r'''{
      "name": "Updated Item",
      "description": "Updated widget description",
      "price": 39.99,
      "tax": 3.50,
      "category": "electronics"
    }'''
    
    # Fuzz strategies
    endpoint_1_put_fuzzed_body = {
        "category": "0123456789",
        "description": "0123456789",
        "name": "0123456789",
        "price": -10,
        "tax": -10
    }
    # Fuzz status codes
    expected_endpoint_1_put_status_code = {
        "category": "40x",
        "description": "40x",
        "name": "40x",
        "price": "40x",
        "tax": "40x"
    }
    # Fuzz status codes for Null values
    expected_endpoint_1_put_null_status_code = {
        "category": "40x",
        "description": "40x",
        "name": "40x",
        "price": "40x",
        "tax": "40x"
    }

    # Execute Request
    endpoint_1_PUT_response = client.send_request(
        url=URL,
        path="/items/1",
        method="PUT",
        body=endpoint_1_PUT_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(endpoint_1_put_fuzzed_body):
        # Execute Request
        endpoint_1_PUT_response = client.send_request(
            url=URL,
            path="/items/1",
            method="PUT",
            body=endpoint_1_PUT_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(endpoint_1_put_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_endpoint_1_put_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(endpoint_1_put_fuzzed_body, key) }'
        )

        # Execute Request
        endpoint_1_PUT_response = client.send_request(
            url=URL,
            path="/items/1",
            method="PUT",
            body=endpoint_1_PUT_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_endpoint_1_put_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_1_put()
