# Generated by Skyramp v1.3.11 on 2026-03-11 12:31:45.246830635 +0000 UTC m=+259.769335105
# Command: skyramp generate integration rest \
# 		--auth-header X-API-Key \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_multi_category_listing.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/fastapi-testb/fastapi-testb/tests/scenario_items-multi-category-listing.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "category": "electronics",
        "description": "Bluetooth earbuds with noise cancellation",
        "name": "Wireless Earbuds",
        "price": 79.99,
        "tax": 7.99
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "category": "clothing",
        "description": "Warm insulated winter jacket",
        "name": "Winter Jacket",
        "price": 149.99,
        "tax": 14.99
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201

    # Request Body
    endpoint_1_POST_2_request_body = r'''{
        "category": "books",
        "description": "Comprehensive Python programming reference",
        "name": "Python Programming Guide",
        "price": 34.99,
        "tax": 2.99
    }'''
    
    # Execute Request
    endpoint_1_POST_2_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="POST",
        body=endpoint_1_POST_2_request_body,
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_POST_2_response.status_code == 201

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/items/",
        method="GET",
        headers={"X-API-Key": ""}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
