# Generated by Skyramp v1.3.11 on 2026-03-09 19:30:48.430076961 +0000 UTC m=+131.015147642
# Command: skyramp generate load rest http://localhost:8000/items/ \
# 		--api-schema http://localhost:8000/openapi.json \
# 		--auth-header X-API-Key \
# 		--default-duration 5 \
# 		--default-num-threads 1 \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_load.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

load_config = skyramp.LoadTestConfig(
    load_duration=5,
    load_num_threads=1,
    load_target_rps=None,
    load_count=None,
    load_rampup_duration=None,
    load_rampup_interval=None
)
# Definition of authentication header
def get_header():
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")
    return headers


def test_endpoint_get(load_test_config:skyramp.LoadTestConfig=load_config):
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()
    scenario = skyramp.AsyncScenario(name="scenario")
    # Add Request to Scenario
    endpoint_GET_response = scenario.add_async_request(
        name="endpoint_GET",
        url=URL,
        path="/items/",
        method="GET",
        headers=headers,
        expected_code="200"
    )
    result = client.send_scenario(
        scenario,
        load_test_config=load_test_config
    )

    print(
        f"""{{"result": {result.get_overall_status()}}}"""
    )




def test_endpoint_post(load_test_config:skyramp.LoadTestConfig=load_config):
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()
    scenario = skyramp.AsyncScenario(name="scenario")
    # Request Body
    endpoint_POST_request_body = r'''{
            "description": "string",
            "name": "string",
            "price": 0,
            "tax": "string"
        }'''
    
    # Add Request to Scenario
    endpoint_POST_response = scenario.add_async_request(
        name="endpoint_POST",
        url=URL,
        path="/items/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers,
        expected_code="201"
    )
    result = client.send_scenario(
        scenario,
        load_test_config=load_test_config
    )

    print(
        f"""{{"result": {result.get_overall_status()}}}"""
    )




def test_items_item_id_get(load_test_config:skyramp.LoadTestConfig=load_config):
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()
    # Declaration of variables
    item_id = 0

    scenario = skyramp.AsyncScenario(name="scenario")
    # Add Request to Scenario
    items_item_id_GET_response = scenario.add_async_request(
        name="items_item_id_GET",
        url=URL,
        path="/items/{item_id}",
        method="GET",
        headers=headers,
        path_params={"item_id": item_id},
        expected_code="200"
    )
    result = client.send_scenario(
        scenario,
        load_test_config=load_test_config
    )

    print(
        f"""{{"result": {result.get_overall_status()}}}"""
    )




def test_items_item_id_put(load_test_config:skyramp.LoadTestConfig=load_config):
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()
    # Declaration of variables
    item_id = 0

    scenario = skyramp.AsyncScenario(name="scenario")
    # Request Body
    items_item_id_PUT_request_body = r'''{
            "description": "string",
            "name": "string",
            "price": 0,
            "tax": "string"
        }'''
    
    # Add Request to Scenario
    items_item_id_PUT_response = scenario.add_async_request(
        name="items_item_id_PUT",
        url=URL,
        path="/items/{item_id}",
        method="PUT",
        body=items_item_id_PUT_request_body,
        headers=headers,
        path_params={"item_id": item_id},
        expected_code="200"
    )
    result = client.send_scenario(
        scenario,
        load_test_config=load_test_config
    )

    print(
        f"""{{"result": {result.get_overall_status()}}}"""
    )




def test_items_item_id_delete(load_test_config:skyramp.LoadTestConfig=load_config):
    # Invocation of Skyramp Client and calling of authentication header
    client = skyramp.Client()
    headers = get_header()
    # Declaration of variables
    item_id = 0

    scenario = skyramp.AsyncScenario(name="scenario")
    # Add Request to Scenario
    items_item_id_DELETE_response = scenario.add_async_request(
        name="items_item_id_DELETE",
        url=URL,
        path="/items/{item_id}",
        method="DELETE",
        headers=headers,
        path_params={"item_id": item_id},
        expected_code="204"
    )
    result = client.send_scenario(
        scenario,
        load_test_config=load_test_config
    )

    print(
        f"""{{"result": {result.get_overall_status()}}}"""
    )


if __name__ == "__main__":
    test_endpoint_get()
    test_endpoint_post()
    test_items_item_id_get()
    test_items_item_id_put()
    test_items_item_id_delete()
