# Generated by Skyramp v1.3.11 on 2026-03-11 13:25:48.970378111 +0000 UTC m=+118.992304489
# Command: skyramp generate contract rest http://localhost:8000/items/1 \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output test_items_put_category_contract.py \
# 		--output-dir /home/runner/work/fastapi-testb/fastapi-testb/tests \
# 		--overwrite \
# 		--request-data {"name":"Updated Laptop","description":"Updated high-performance laptop","price":1199.99,"tax":107.99,"category":"electronics"} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /items/1 PUT
def test_endpoint_1_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_PUT_request_body = r'''{
        "category": "electronics",
        "description": "Updated high-performance laptop",
        "name": "Updated Laptop",
        "price": 1199.99,
        "tax": 107.99
    }'''

    # Execute Request
    endpoint_1_PUT_response = client.send_request(
        url=URL,
        path="/items/1",
        method="PUT",
        body=endpoint_1_PUT_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_1_PUT_response.status_code == 200

if __name__ == "__main__":
    test_endpoint_1_put()
